#pragma once


#define NUM_OF_HARDCODED_SOUNDS 7
//#define SOUND_BUTTON_INDENT 0.25
//#define SOUND_BUTTON_WIDTH 0.08

#define BUTTON_INDENT 0.03

#define BUTTON_WIDTH 0.08

//#define SOUND_NUM_INDENT 0.22
#define SOUND_NUM_INDENT 0.24

#define NUM_OF_MENU_POSITIONS 11
#define NUM_OF_REC_POSITIONS 3
#define NUM_OF_POS_TO_THE_LEFT_FOR_FILESAMPLES 4
#define NUM_OF_REC_MODES 3