#pragma once


#define NUM_OF_SOUNDS 7
//#define SOUND_BUTTON_INDENT 0.25
//#define SOUND_BUTTON_WIDTH 0.08

#define BUTTON_INDENT 0.03

#define BUTTON_WIDTH 0.08

#define SOUND_NUM_INDENT 0.22
#define PICTOGRAMS_INDENT 0.0001

#define NUM_OF_MENU_POSITIONS 12